# Copy this file to ~/.pubtrends-datasets/config.properties
# Change these two lines so they contain your home directory
geometadb_path = ~/geodatasets/geometadb.sqlite
test_geometadb_path = ~/geodatasets/testgeometadb.sqlite
max_ncbi_connections = 10
dataset_parser_workers = 2
small_dataset_parser_workers = 8
big_dataset_parser_workers = 2
big_gzip_threshold_mb = 65.0
dataset_download_folder = ~/geodatasets/soft_files
show_backfill_progress = true
chunk_size = 2
dont_redownload = false

